In [1]:
import pandas as pd

In [2]:
codes = pd.read_hdf("D:\\TICK_MAIN\\TICK_MAIN\\2019\\04\\20190426_kor_stock.h5", "codes")
codes

,hname,shcode,expcode,etfgubun,uplmtprice,dnlmtprice,jnilclose,memedan,recprice,gubun
00806K,대덕전자1우,00806K,KR700806K010,0,7860,4240,6050,00001,6050,1
098560,TIGER 방송통신,098560,KR7098560006,1,12265,6605,9435,00001,9435,1
004250,NPC,004250,KR7004250007,0,5260,2835,4050,00001,4050,1
005750,대림B&Co,005750,KR7005750005,0,6730,3630,5180,00001,5180,1
182480,TIGER 미국MSCI리츠(,182480,KR7182480004,1,17405,9375,13390,00001,13390,1
310970,TIGER MSCI Korea TR,310970,KR7310970009,1,14250,7680,10965,00001,10965,1
012510,더존비즈온,012510,KR7012510004,0,72800,39200,56000,00001,56000,1
292570,TIGER 일본엔선물레버,292570,KR7292570009,1,16465,4125,10295,00001,10295,1
000950,전방,000950,KR7000950006,0,24150,13050,18600,00001,18600,1
319870,KBSTAR KRX300미국달,319870,KR7319870002,1,13440,7240,10340,00001,10340,1
269530,ARIRANG S&P글로벌인,269530,KR7269530002,1,14435,7775,11105,00001,11105,1
226490,KODEX 코스피,226490,KR7226490001,1,29150,15700,22425,00001,22425,1
071840,롯데하이마트,071840,KR7071840003,0,62400,33600,48000,00001,48000,1
005390,신성통상,005390,KR7005390000,0,1235,668,953,00001,953,1
109070,컨버즈,109070,KR7109070003,0,4235,2285,3260,00001,3260,1
138920,KODEX 콩선물(H),138920,KR7138920004,1,10670,5750,8210,00001,8210,1
007980,태평양물산,007980,KR7007980006,0,3640,1960,2800,00001,2800,1
304760,HANARO KRX300,304760,KR7304760002,1,17295,9315,13305,00001,13305,1
003560,IHQ,003560,KR7003560000,0,2885,1555,2220,00001,2220,1
011160,두산건설,011160,KR7011160009,0,1650,890,1270,00001,1270,1
003160,디아이,003160,KR7003160009,0,5440,2930,4185,00001,4185,1
010060,OCI,010060,KR7010060002,0,120500,65100,92900,00001,92900,1
550054,QV 레버리지 MSCI 선,550054,KRG552100544,2,15770,3950,9860,00001,9860,1
029780,삼성카드,029780,KR7029780004,0,48800,26300,37550,00001,37550,1
002140,고려산업,002140,KR7002140002,0,3155,1705,2430,00001,2430,1
315960,KBSTAR 대형고배당10T,315960,KR7315960005,1,14010,7550,10780,00001,10780,1
058850,KTcs,058850,KR7058850009,0,3150,1700,2425,00001,2425,1
004360,세방,004360,KR7004360004,0,18750,10150,14450,00001,14450,1
168490,한국패러랠,168490,KR7168490001,0,2940,1590,2265,00001,2265,1
550014,QV 바이오 TOP5 ETN,550014,KRG551100149,2,18420,9920,14170,00001,14170,1
...,...,...,...,...,...,...,...,...,...,...
008060,대덕전자,008060,KR7008060006,0,12700,6860,9790,00001,9790,1
319640,TIGER 골드선물(H),319640,KR7319640009,1,12745,6865,9805,00001,9805,1
004910,조광페인트,004910,KR7004910006,0,9020,4860,6940,00001,6940,1
003460,유화증권,003460,KR7003460003,0,16500,8900,12700,00001,12700,1
015760,한국전력,015760,KR7015760002,0,36200,19500,27850,00001,27850,1
000210,대림산업,000210,KR7000210005,0,121500,65500,93500,00001,93500,1
016710,대성홀딩스,016710,KR7016710006,0,10200,5500,7850,00001,7850,1
007460,에이프로젠 KIC,007460,KR7007460009,0,5200,2800,4000,00001,4000,1
016450,한세예스24홀딩스,016450,KR7016450009,0,12600,6810,9720,00001,9720,1
530059,삼성 K200 Put 1908-0,530059,KRG531100599,2,12450,6710,9580,00001,9580,1
244580,KODEX 바이오,244580,KR7244580007,1,14020,7550,10785,00001,10785,1
003200,일신방직,003200,KR7003200003,0,135000,73000,104000,00001,104000,1
500026,신한 인버스 MSCI 인,500026,KRG507100268,2,11465,6175,8820,00001,8820,1
005610,SPC삼립,005610,KR7005610001,0,167000,90000,128500,00001,128500,1
213500,한솔제지,213500,KR7213500002,0,19500,10500,15000,00001,15000,1
006800,미래에셋대우,006800,KR7006800007,0,10050,5430,7750,00001,7750,1
000070,삼양홀딩스,000070,KR7000070003,0,104500,56500,80600,00001,80600,1
175330,JB금융지주,175330,KR7175330000,0,7260,3920,5590,00001,5590,1
241560,두산밥캣,241560,KR7241560002,0,40850,22050,31450,00001,31450,1
082640,동양생명,082640,KR7082640004,0,5810,3135,4475,00001,4475,1
214330,금호에이치티,214330,KR7214330003,0,8070,4350,6210,00001,6210,1
004200,고려개발,004200,KR7004200002,0,6340,3420,4880,00001,4880,1
300290,KBSTAR 중소형모멘텀,300290,KR7300290004,1,12815,6905,9860,00001,9860,1
000150,두산,000150,KR7000150003,0,134500,72500,103500,00001,103500,1
500042,신한 코스피 콘도르 6,500042,KRG501100421,2,12575,6775,9675,00001,9675,1
530063,삼성 레버리지 구리,530063,KRG532400634,2,17340,4340,10840,00001,10840,1
042700,한미반도체,042700,KR7042700005,0,12050,6500,9280,00001,9280,1
153270,KOSEF 코스피100,153270,KR7153270004,1,28760,15490,22125,00001,22125,1
000087,하이트진로2우B,000087,KR7000082008,0,20800,11200,16000,00001,16000,1
138250,엔에스쇼핑,138250,KR7138250006,0,18550,10050,14300,00001,14300,1

In [6]:
codes.loc['005930','hname']

'삼성전자'

In [4]:
pd.read_hdf("D:\\TICK_MAIN\\TICK_MAIN\\2019\\04\\20190426_kor_stock.h5", "005930_lob")

                                     offer_total_v  bid_total_v sim_call  \
time_api datetime_sys
08:45:15 2019-04-26 08:45:15.113173              0            0        3
         2019-04-26 08:45:15.620598              0            0        3
         2019-04-26 08:45:15.866570              0            0        3
08:45:16 2019-04-26 08:45:16.118928              0            0        3
         2019-04-26 08:45:16.368585              0            0        3
         2019-04-26 08:45:16.623923              0            0        3
         2019-04-26 08:45:16.871660              0            0        3
         2019-04-26 08:45:17.127708              0            0        3
08:45:17 2019-04-26 08:45:17.631700              0            0        3
         2019-04-26 08:45:17.881888              0            0        3
08:45:18 2019-04-26 08:45:18.384734              0            0        3
         2019-04-26 08:45:18.637736              0            0        3
         2019-04-26 08:45:18.889977              0            0        3
08:45:19 2019-04-26 08:45:19.138958              0            0        3
         2019-04-26 08:45:19.649397              0            0        3
         2019-04-26 08:45:19.900332              0            0        3
08:45:20 2019-04-26 08:45:20.153111              0            0        3
         2019-04-26 08:45:20.406698              0            0        3
         2019-04-26 08:45:20.663413              0            0        3
08:45:21 2019-04-26 08:45:21.161067              0            0        3
         2019-04-26 08:45:21.417397              0            0        3
08:45:22 2019-04-26 08:45:22.427603              0            0        3
         2019-04-26 08:45:22.932538              0            0        3
08:45:23 2019-04-26 08:45:23.182410              0            0        3
         2019-04-26 08:45:23.438672              0            0        3
         2019-04-26 08:45:23.688145              0            0        3
         2019-04-26 08:45:23.945789              0            0        3
08:45:24 2019-04-26 08:45:24.193433              0            0        3
         2019-04-26 08:45:24.954639              0            0        3
08:45:25 2019-04-26 08:45:25.208982              0            0        3
...                                            ...          ...      ...
15:40:23 2019-04-26 15:40:23.349758         620904       523412        2
15:40:29 2019-04-26 15:40:29.909676         620904       523412        2
15:40:33 2019-04-26 15:40:33.448246         620904       523412        2
         2019-04-26 15:40:33.947455         620904       523412        2
15:41:23 2019-04-26 15:41:23.909825         620904       523412        2
         2019-04-26 15:41:24.161252         620904       523412        2
15:41:24 2019-04-26 15:41:25.173458         620904       523412        2
15:41:29 2019-04-26 15:41:29.463321         620904       523412        2
15:41:35 2019-04-26 15:41:36.022619         620904       523412        2
15:41:38 2019-04-26 15:41:38.797983         620904       523412        2
15:41:40 2019-04-26 15:41:40.562812         620904       523412        2
15:41:58 2019-04-26 15:41:58.729488         620904       523412        2
15:42:11 2019-04-26 15:42:11.849557         620904       523412        2
15:42:19 2019-04-26 15:42:19.418081         620904       523412        2
15:42:23 2019-04-26 15:42:23.452833         620904       523412        2
15:42:27 2019-04-26 15:42:27.238621         620904       523412        2
         2019-04-26 15:42:27.992791         620904       523412        2
15:42:51 2019-04-26 15:42:51.708159         620904       523412        2
15:42:55 2019-04-26 15:42:56.001243         620904       523412        2
15:43:02 2019-04-26 15:43:02.557115         620904       523412        2
15:43:25 2019-04-26 15:43:25.560398         620904       523412        2
15:43:30 2019-04-26 15:43:30.858136         620904       523412        2
15:43:58 2019-04-26 15:43:58.611757         620904       523412        2
15:44:03 2019-04-26 15:44:03.406452         620904       523412        2
15:44:18 2019-04-26 15:44:18.793556         620904       523412        2
15:44:21 2019-04-26 15:44:21.819026         620904       523412        2
15:45:00 2019-04-26 15:45:00.920077         620904       523412        2
15:45:02 2019-04-26 15:45:02.185806         620904       523412        2
15:45:27 2019-04-26 15:45:27.414947         620904       523412        2
15:45:31 2019-04-26 15:45:31.954720         620904       523412        2

                                     offer_01_p  offer_02_p  offer_03_p  \
time_api datetime_sys
08:45:15 2019-04-26 08:45:15.113173       43550       43700       43750
         2019-04-26 08:45:15.620598       43550       43700       43750
         2019-04-26 08:45:15.866570       43550       43700       43750
08:45:16 2019-04-26 08:45:16.118928       43550       43700       43750
         2019-04-26 08:45:16.368585       43550       43700       43750
         2019-04-26 08:45:16.623923       43550       43700       43750
         2019-04-26 08:45:16.871660       43550       43700       43750
         2019-04-26 08:45:17.127708       43550       43700       43750
08:45:17 2019-04-26 08:45:17.631700       43550       43700       43750
         2019-04-26 08:45:17.881888       43550       43700       43750
08:45:18 2019-04-26 08:45:18.384734       43550       43700       43750
         2019-04-26 08:45:18.637736       43550       43700       43750
         2019-04-26 08:45:18.889977       43550       43700       43750
08:45:19 2019-04-26 08:45:19.138958       43550       43700       43750
         2019-04-26 08:45:19.649397       43550       43700       43750
         2019-04-26 08:45:19.900332       43550       43700       43750
08:45:20 2019-04-26 08:45:20.153111       43550       43700       43750
         2019-04-26 08:45:20.406698       43550       43700       43750
         2019-04-26 08:45:20.663413       43550       43700       43750
08:45:21 2019-04-26 08:45:21.161067       43550       43700       43750
         2019-04-26 08:45:21.417397       43550       43700       43750
08:45:22 2019-04-26 08:45:22.427603       43550       43700       43750
         2019-04-26 08:45:22.932538       43550       43700       43750
08:45:23 2019-04-26 08:45:23.182410       43550       43700       43750
         2019-04-26 08:45:23.438672       43550       43700       43750
         2019-04-26 08:45:23.688145       43550       43700       43750
         2019-04-26 08:45:23.945789       43550       43700       43750
08:45:24 2019-04-26 08:45:24.193433       43550       43700       43750
         2019-04-26 08:45:24.954639       43550       43700       43750
08:45:25 2019-04-26 08:45:25.208982       43550       43700       43750
...                                         ...         ...         ...
15:40:23 2019-04-26 15:40:23.349758       44850       44900       44950
15:40:29 2019-04-26 15:40:29.909676       44850       44900       44950
15:40:33 2019-04-26 15:40:33.448246       44850       44900       44950
         2019-04-26 15:40:33.947455       44850       44900       44950
15:41:23 2019-04-26 15:41:23.909825       44850       44900       44950
         2019-04-26 15:41:24.161252       44850       44900       44950
15:41:24 2019-04-26 15:41:25.173458       44850       44900       44950
15:41:29 2019-04-26 15:41:29.463321       44850       44900       44950
15:41:35 2019-04-26 15:41:36.022619       44850       44900       44950
15:41:38 2019-04-26 15:41:38.797983       44850       44900       44950
15:41:40 2019-04-26 15:41:40.562812       44850       44900       44950
15:41:58 2019-04-26 15:41:58.729488       44850       44900       44950
15:42:11 2019-04-26 15:42:11.849557       44850       44900       44950
15:42:19 2019-04-26 15:42:19.418081       44850       44900       44950
15:42:23 2019-04-26 15:42:23.452833       44850       44900       44950
15:42:27 2019-04-26 15:42:27.238621       44850       44900       44950
         2019-04-26 15:42:27.992791       44850       44900       44950
15:42:51 2019-04-26 15:42:51.708159       44850       44900       44950
15:42:55 2019-04-26 15:42:56.001243       44850       44900       44950
15:43:02 2019-04-26 15:43:02.557115       44850       44900       44950
15:43:25 2019-04-26 15:43:25.560398       44850       44900       44950
15:43:30 2019-04-26 15:43:30.858136       44850       44900       44950
15:43:58 2019-04-26 15:43:58.611757       44850       44900       44950
15:44:03 2019-04-26 15:44:03.406452       44850       44900       44950
15:44:18 2019-04-26 15:44:18.793556       44850       44900       44950
15:44:21 2019-04-26 15:44:21.819026       44850       44900       44950
15:45:00 2019-04-26 15:45:00.920077       44850       44900       44950
15:45:02 2019-04-26 15:45:02.185806       44850       44900       44950
15:45:27 2019-04-26 15:45:27.414947       44850       44900       44950
15:45:31 2019-04-26 15:45:31.954720       44850       44900       44950

                                     offer_04_p  offer_05_p  offer_06_p  \
time_api datetime_sys
08:45:15 2019-04-26 08:45:15.113173           0           0           0
         2019-04-26 08:45:15.620598           0           0           0
         2019-04-26 08:45:15.866570           0           0           0
08:45:16 2019-04-26 08:45:16.118928           0           0           0
         2019-04-26 08:45:16.368585           0           0           0
         2019-04-26 08:45:16.623923           0           0           0
         2019-04-26 08:45:16.871660           0           0           0
         2019-04-26 08:45:17.127708           0           0           0
08:45:17 2019-04-26 08:45:17.631700           0           0           0
         2019-04-26 08:45:17.881888           0           0           0
08:45:18 2019-04-26 08:45:18.384734           0           0           0
         2019-04-26 08:45:18.637736           0           0           0
         2019-04-26 08:45:18.889977           0           0           0
08:45:19 2019-04-26 08:45:19.138958           0           0           0
         2019-04-26 08:45:19.649397           0           0           0
         2019-04-26 08:45:19.900332           0           0           0
08:45:20 2019-04-26 08:45:20.153111           0           0           0
         2019-04-26 08:45:20.406698           0           0           0
         2019-04-26 08:45:20.663413           0           0           0
08:45:21 2019-04-26 08:45:21.161067           0           0           0
         2019-04-26 08:45:21.417397           0           0           0
08:45:22 2019-04-26 08:45:22.427603           0           0           0
         2019-04-26 08:45:22.932538           0           0           0
08:45:23 2019-04-26 08:45:23.182410           0           0           0
         2019-04-26 08:45:23.438672           0           0           0
         2019-04-26 08:45:23.688145           0           0           0
         2019-04-26 08:45:23.945789           0           0           0
08:45:24 2019-04-26 08:45:24.193433           0           0           0
         2019-04-26 08:45:24.954639           0           0           0
08:45:25 2019-04-26 08:45:25.208982           0           0           0
...                                         ...         ...         ...
15:40:23 2019-04-26 15:40:23.349758       45000       45050       45100
15:40:29 2019-04-26 15:40:29.909676       45000       45050       45100
15:40:33 2019-04-26 15:40:33.448246       45000       45050       45100
         2019-04-26 15:40:33.947455       45000       45050       45100
15:41:23 2019-04-26 15:41:23.909825       45000       45050       45100
         2019-04-26 15:41:24.161252       45000       45050       45100
15:41:24 2019-04-26 15:41:25.173458       45000       45050       45100
15:41:29 2019-04-26 15:41:29.463321       45000       45050       45100
15:41:35 2019-04-26 15:41:36.022619       45000       45050       45100
15:41:38 2019-04-26 15:41:38.797983       45000       45050       45100
15:41:40 2019-04-26 15:41:40.562812       45000       45050       45100
15:41:58 2019-04-26 15:41:58.729488       45000       45050       45100
15:42:11 2019-04-26 15:42:11.849557       45000       45050       45100
15:42:19 2019-04-26 15:42:19.418081       45000       45050       45100
15:42:23 2019-04-26 15:42:23.452833       45000       45050       45100
15:42:27 2019-04-26 15:42:27.238621       45000       45050       45100
         2019-04-26 15:42:27.992791       45000       45050       45100
15:42:51 2019-04-26 15:42:51.708159       45000       45050       45100
15:42:55 2019-04-26 15:42:56.001243       45000       45050       45100
15:43:02 2019-04-26 15:43:02.557115       45000       45050       45100
15:43:25 2019-04-26 15:43:25.560398       45000       45050       45100
15:43:30 2019-04-26 15:43:30.858136       45000       45050       45100
15:43:58 2019-04-26 15:43:58.611757       45000       45050       45100
15:44:03 2019-04-26 15:44:03.406452       45000       45050       45100
15:44:18 2019-04-26 15:44:18.793556       45000       45050       45100
15:44:21 2019-04-26 15:44:21.819026       45000       45050       45100
15:45:00 2019-04-26 15:45:00.920077       45000       45050       45100
15:45:02 2019-04-26 15:45:02.185806       45000       45050       45100
15:45:27 2019-04-26 15:45:27.414947       45000       45050       45100
15:45:31 2019-04-26 15:45:31.954720       45000       45050       45100

                                     offer_07_p  ...  bid_01_v  bid_02_v  \
time_api datetime_sys                            ...
08:45:15 2019-04-26 08:45:15.113173           0  ...     18381      2854
         2019-04-26 08:45:15.620598           0  ...     18581      2854
         2019-04-26 08:45:15.866570           0  ...     18581      2854
08:45:16 2019-04-26 08:45:16.118928           0  ...     18591      2854
         2019-04-26 08:45:16.368585           0  ...     18615      2854
         2019-04-26 08:45:16.623923           0  ...     18616      2854
         2019-04-26 08:45:16.871660           0  ...     18766      2854
         2019-04-26 08:45:17.127708           0  ...     18766      2854
08:45:17 2019-04-26 08:45:17.631700           0  ...     18767      2854
         2019-04-26 08:45:17.881888           0  ...     18769      2854
08:45:18 2019-04-26 08:45:18.384734           0  ...     18769      2854
         2019-04-26 08:45:18.637736           0  ...     18789      2854
         2019-04-26 08:45:18.889977           0  ...     18789      2854
08:45:19 2019-04-26 08:45:19.138958           0  ...     18789      2854
         2019-04-26 08:45:19.649397           0  ...     18789      2854
         2019-04-26 08:45:19.900332           0  ...     18764      2854
08:45:20 2019-04-26 08:45:20.153111           0  ...     18764      2854
         2019-04-26 08:45:20.406698           0  ...     18768      2854
         2019-04-26 08:45:20.663413           0  ...     18767      2854
08:45:21 2019-04-26 08:45:21.161067           0  ...     18767      2854
         2019-04-26 08:45:21.417397           0  ...     18897      2854
08:45:22 2019-04-26 08:45:22.427603           0  ...     19007      2854
         2019-04-26 08:45:22.932538           0  ...     19010      2854
08:45:23 2019-04-26 08:45:23.182410           0  ...     19010      2874
         2019-04-26 08:45:23.438672           0  ...     19010      2874
         2019-04-26 08:45:23.688145           0  ...     19010      2874
         2019-04-26 08:45:23.945789           0  ...     19030      2874
08:45:24 2019-04-26 08:45:24.193433           0  ...     19030      2874
         2019-04-26 08:45:24.954639           0  ...     19430      2874
08:45:25 2019-04-26 08:45:25.208982           0  ...     19430      2874
...                                         ...  ...       ...       ...
15:40:23 2019-04-26 15:40:23.349758       45150  ...     11943     75236
15:40:29 2019-04-26 15:40:29.909676       45150  ...     11943     75236
15:40:33 2019-04-26 15:40:33.448246       45150  ...     11943     75236
         2019-04-26 15:40:33.947455       45150  ...     11943     75236
15:41:23 2019-04-26 15:41:23.909825       45150  ...     11943     75236
         2019-04-26 15:41:24.161252       45150  ...     11943     75236
15:41:24 2019-04-26 15:41:25.173458       45150  ...     11943     75236
15:41:29 2019-04-26 15:41:29.463321       45150  ...     11943     75236
15:41:35 2019-04-26 15:41:36.022619       45150  ...     11943     75236
15:41:38 2019-04-26 15:41:38.797983       45150  ...     11943     75236
15:41:40 2019-04-26 15:41:40.562812       45150  ...     11943     75236
15:41:58 2019-04-26 15:41:58.729488       45150  ...     11943     75236
15:42:11 2019-04-26 15:42:11.849557       45150  ...     11943     75236
15:42:19 2019-04-26 15:42:19.418081       45150  ...     11943     75236
15:42:23 2019-04-26 15:42:23.452833       45150  ...     11943     75236
15:42:27 2019-04-26 15:42:27.238621       45150  ...     11943     75236
         2019-04-26 15:42:27.992791       45150  ...     11943     75236
15:42:51 2019-04-26 15:42:51.708159       45150  ...     11943     75236
15:42:55 2019-04-26 15:42:56.001243       45150  ...     11943     75236
15:43:02 2019-04-26 15:43:02.557115       45150  ...     11943     75236
15:43:25 2019-04-26 15:43:25.560398       45150  ...     11943     75236
15:43:30 2019-04-26 15:43:30.858136       45150  ...     11943     75236
15:43:58 2019-04-26 15:43:58.611757       45150  ...     11943     75236
15:44:03 2019-04-26 15:44:03.406452       45150  ...     11943     75236
15:44:18 2019-04-26 15:44:18.793556       45150  ...     11943     75236
15:44:21 2019-04-26 15:44:21.819026       45150  ...     11943     75236
15:45:00 2019-04-26 15:45:00.920077       45150  ...     11943     75236
15:45:02 2019-04-26 15:45:02.185806       45150  ...     11943     75236
15:45:27 2019-04-26 15:45:27.414947       45150  ...     11943     75236
15:45:31 2019-04-26 15:45:31.954720       45150  ...     11943     75236

                                     bid_03_v  bid_04_v  bid_05_v  bid_06_v  \
time_api datetime_sys
08:45:15 2019-04-26 08:45:15.113173      7316         0         0         0
         2019-04-26 08:45:15.620598      7316         0         0         0
         2019-04-26 08:45:15.866570      7316         0         0         0
08:45:16 2019-04-26 08:45:16.118928      7316         0         0         0
         2019-04-26 08:45:16.368585      7227         0         0         0
         2019-04-26 08:45:16.623923      7227         0         0         0
         2019-04-26 08:45:16.871660      7227         0         0         0
         2019-04-26 08:45:17.127708      7227         0         0         0
08:45:17 2019-04-26 08:45:17.631700      7227         0         0         0
         2019-04-26 08:45:17.881888      7227         0         0         0
08:45:18 2019-04-26 08:45:18.384734      7227         0         0         0
         2019-04-26 08:45:18.637736      7227         0         0         0
         2019-04-26 08:45:18.889977      7227         0         0         0
08:45:19 2019-04-26 08:45:19.138958      7227         0         0         0
         2019-04-26 08:45:19.649397      7227         0         0         0
         2019-04-26 08:45:19.900332      7227         0         0         0
08:45:20 2019-04-26 08:45:20.153111      7227         0         0         0
         2019-04-26 08:45:20.406698      7227         0         0         0
         2019-04-26 08:45:20.663413      7227         0         0         0
08:45:21 2019-04-26 08:45:21.161067      7227         0         0         0
         2019-04-26 08:45:21.417397      7227         0         0         0
08:45:22 2019-04-26 08:45:22.427603      7227         0         0         0
         2019-04-26 08:45:22.932538      7227         0         0         0

In [5]:
pd.read_hdf("D:\\TICK_MAIN\\TICK_MAIN\\2019\\04\\20190426_kor_stock.h5", "005930_tr")

                                     price   volume  cum_volume  cum_value  \
time_api datetime_sys
09:00:18 2019-04-26 09:00:18.441979  44200   474877      485319      21456
         2019-04-26 09:00:18.443118  44200       20      485339      21457
         2019-04-26 09:00:18.443742  44200        1      485340      21457
         2019-04-26 09:00:18.444387  44300        2      485342      21457
         2019-04-26 09:00:18.445009  44200       10      485352      21457
         2019-04-26 09:00:18.445613  44250        1      485353      21457
         2019-04-26 09:00:18.446243  44250        2      485355      21457
         2019-04-26 09:00:18.446842  44300       21      485376      21458
         2019-04-26 09:00:18.447461  44300       10      485386      21459
         2019-04-26 09:00:18.448065  44300        1      485387      21459
         2019-04-26 09:00:18.448718  44250        3      485390      21459
         2019-04-26 09:00:18.449321  44250        3      485393      21459
         2019-04-26 09:00:18.449942  44300        1      485394      21459
         2019-04-26 09:00:18.450560  44300       50      485444      21461
         2019-04-26 09:00:18.659397  44300     1223      486667      21516
         2019-04-26 09:00:18.660080  44250      657      487324      21545
         2019-04-26 09:00:18.660684  44300      681      488005      21575
         2019-04-26 09:00:18.945871  44300      195      488200      21583
         2019-04-26 09:00:18.946483  44300      306      488506      21597
09:00:19 2019-04-26 09:00:19.190320  44300        5      488511      21597
         2019-04-26 09:00:19.190934  44300        3      488514      21597
         2019-04-26 09:00:19.443963  44250      918      489432      21638
         2019-04-26 09:00:20.022379  44250      676      490108      21668
         2019-04-26 09:00:20.022982  44250      150      490258      21674
         2019-04-26 09:00:20.023565  44250     3747      494005      21840
         2019-04-26 09:00:20.024193  44250      121      494126      21846
09:00:20 2019-04-26 09:00:20.213067  44250      134      494260      21852
         2019-04-26 09:00:20.213710  44250      131      494391      21857
         2019-04-26 09:00:20.214333  44250      119      494510      21863
         2019-04-26 09:00:20.215005  44250      128      494638      21868
...                                    ...      ...         ...        ...
15:19:57 2019-04-26 15:19:57.732142  44900      705     8226528     366160
15:19:58 2019-04-26 15:19:58.518929  44850       44     8226572     366162
         2019-04-26 15:19:58.761034  44900      112     8226684     366167
         2019-04-26 15:19:58.761521  44850       53     8226737     366169
         2019-04-26 15:19:58.762011  44850       50     8226787     366171
         2019-04-26 15:19:59.041627  44900      112     8226899     366177
15:19:59 2019-04-26 15:19:59.296162  44900      112     8227011     366182
         2019-04-26 15:19:59.551843  44900      112     8227123     366187
15:30:16 2019-04-26 15:30:16.459508  44850  1132221     9359344     416967
15:40:00 2019-04-26 15:40:00.394862  44850     4545     9363889     417171
15:40:03 2019-04-26 15:40:04.179730  44850      202     9364091     417180
15:40:05 2019-04-26 15:40:05.183926  44850        1     9364092     417180
15:40:08 2019-04-26 15:40:08.460073  44850        2     9364094     417180
15:40:33 2019-04-26 15:40:33.447601  44850        1     9364095     417180
         2019-04-26 15:40:33.946604  44850       27     9364122     417181
15:41:23 2019-04-26 15:41:23.909181  44850        1     9364123     417181
15:41:24 2019-04-26 15:41:25.172824  44850        5     9364128     417181
15:41:29 2019-04-26 15:41:29.462690  44850        2     9364130     417181
15:41:38 2019-04-26 15:41:38.797371  44850       50     9364180     417184
15:41:40 2019-04-26 15:41:40.561732  44850       96     9364276     417188
15:42:11 2019-04-26 15:42:11.847501  44850       10     9364286     417188
15:42:23 2019-04-26 15:42:23.451729  44850       66     9364352     417191
15:43:02 2019-04-26 15:43:02.556096  44850       52     9364404     417194
15:43:25 2019-04-26 15:43:25.559441  44850      100     9364504     417198
15:43:30 2019-04-26 15:43:30.857148  44850        5     9364509     417198
15:43:58 2019-04-26 15:43:58.610704  44850       12     9364521     417199
15:44:18 2019-04-26 15:44:18.792572  44850        2     9364523     417199
15:45:00 2019-04-26 15:45:02.439976  44850        3     9364526     417199
15:45:01 2019-04-26 15:45:02.440602  44850        1     9364527     417199
15:45:27 2019-04-26 15:45:27.413961  44850      723     9365250     417232

                                    tr_type  w_avg_price  bid_1_price  \
time_api datetime_sys
09:00:18 2019-04-26 09:00:18.441979                44210        44200
         2019-04-26 09:00:18.443118       -        44210        44200
         2019-04-26 09:00:18.443742       -        44210        44200
         2019-04-26 09:00:18.444387       +        44210        44200
         2019-04-26 09:00:18.445009       -        44210        44200
         2019-04-26 09:00:18.445613       +        44210        44200
         2019-04-26 09:00:18.446243       +        44210        44200
         2019-04-26 09:00:18.446842       +        44210        44200
         2019-04-26 09:00:18.447461       +        44210        44250
         2019-04-26 09:00:18.448065       +        44210        44250
         2019-04-26 09:00:18.448718       -        44210        44250
         2019-04-26 09:00:18.449321       -        44210        44250
         2019-04-26 09:00:18.449942       +        44210        44250
         2019-04-26 09:00:18.450560       +        44210        44250
         2019-04-26 09:00:18.659397       +        44210        44250
         2019-04-26 09:00:18.660080       -        44210        44250
         2019-04-26 09:00:18.660684       +        44211        44250
         2019-04-26 09:00:18.945871       +        44211        44250
         2019-04-26 09:00:18.946483       +        44211        44250
09:00:19 2019-04-26 09:00:19.190320       +        44211        44250
         2019-04-26 09:00:19.190934       +        44211        44250
         2019-04-26 09:00:19.443963       -        44211        44250
         2019-04-26 09:00:20.022379       -        44211        44200
         2019-04-26 09:00:20.022982       -        44211        44200
         2019-04-26 09:00:20.023565       -        44211        44200
         2019-04-26 09:00:20.024193       -        44211        44200
09:00:20 2019-04-26 09:00:20.213067       -        44211        44200
         2019-04-26 09:00:20.213710       -        44211        44200
         2019-04-26 09:00:20.214333       -        44211        44200
         2019-04-26 09:00:20.215005       -        44211        44200
...                                     ...          ...          ...
15:19:57 2019-04-26 15:19:57.732142       +        44510        44850
15:19:58 2019-04-26 15:19:58.518929       -        44510        44850
         2019-04-26 15:19:58.761034       +        44510        44850
         2019-04-26 15:19:58.761521       -        44510        44850
         2019-04-26 15:19:58.762011       -        44510        44850
         2019-04-26 15:19:59.041627       +        44510        44850
15:19:59 2019-04-26 15:19:59.296162       +        44510        44850
         2019-04-26 15:19:59.551843       +        44510        44850
15:30:16 2019-04-26 15:30:16.459508                44551        44800
15:40:00 2019-04-26 15:40:00.394862                44551        44800
15:40:03 2019-04-26 15:40:04.179730       -        44551        44800
15:40:05 2019-04-26 15:40:05.183926       +        44551        44800
15:40:08 2019-04-26 15:40:08.460073       +        44551        44800
15:40:33 2019-04-26 15:40:33.447601       +        44551        44800
         2019-04-26 15:40:33.946604       +        44551        44800
15:41:23 2019-04-26 15:41:23.909181       +        44551        44800
15:41:24 2019-04-26 15:41:25.172824       +        44551        44800
15:41:29 2019-04-26 15:41:29.462690       +        44551        44800
15:41:38 2019-04-26 15:41:38.797371       +        44552        44800
15:41:40 2019-04-26 15:41:40.561732       +        44552        44800
15:42:11 2019-04-26 15:42:11.847501       +        44552        44800
15:42:23 2019-04-26 15:42:23.451729       +        44552        44800
15:43:02 2019-04-26 15:43:02.556096       +        44552        44800
15:43:25 2019-04-26 15:43:25.559441       +        44552        44800
15:43:30 2019-04-26 15:43:30.857148       +        44552        44800
15:43:58 2019-04-26 15:43:58.610704       +        44552        44800
15:44:18 2019-04-26 15:44:18.792572       +        44552        44800
15:45:00 2019-04-26 15:45:02.439976       +        44552        44800
15:45:01 2019-04-26 15:45:02.440602       +        44552        44800
15:45:27 2019-04-26 15:45:27.413961       +        44552        44800

                                     offer_1_price
time_api datetime_sys
09:00:18 2019-04-26 09:00:18.441979          44300
         2019-04-26 09:00:18.443118          44300
         2019-04-26 09:00:18.443742          44300
         2019-04-26 09:00:18.444387          44300
         2019-04-26 09:00:18.445009          44300
         2019-04-26 09:00:18.445613          44250
         2019-04-26 09:00:18.446243          44250
         2019-04-26 09:00:18.446842          44300
         2019-04-26 09:00:18.447461          44300
         2019-04-26 09:00:18.448065          44300
         2019-04-26 09:00:18.448718          44300
         2019-04-26 09:00:18.449321          44300
         2019-04-26 09:00:18.449942          44300
         2019-04-26 09:00:18.450560          44300
         2019-04-26 09:00:18.659397          44300
         2019-04-26 09:00:18.660080          44300
         2019-04-26 09:00:18.660684          44300
         2019-04-26 09:00:18.945871          44300
         2019-04-26 09:00:18.946483          44300
09:00:19 2019-04-26 09:00:19.190320          44300
         2019-04-26 09:00:19.190934          44300
         2019-04-26 09:00:19.443963          44300
         2019-04-26 09:00:20.022379          44250
         2019-04-26 09:00:20.022982          44250
         2019-04-26 09:00:20.023565          44250
         2019-04-26 09:00:20.024193          44250
09:00:20 2019-04-26 09:00:20.213067          44250
         2019-04-26 09:00:20.213710          44250
         2019-04-26 09:00:20.214333          44250
         2019-04-26 09:00:20.215005          44250
...                                            ...
15:19:57 2019-04-26 15:19:57.732142          44900
15:19:58 2019-04-26 15:19:58.518929          44900
         2019-04-26 15:19:58.761034          44900
         2019-04-26 15:19:58.761521          44900
         2019-04-26 15:19:58.762011          44900
         2019-04-26 15:19:59.041627          44900
15:19:59 2019-04-26 15:19:59.296162          44900
         2019-04-26 15:19:59.551843          44900
15:30:16 2019-04-26 15:30:16.459508          44850
15:40:00 2019-04-26 15:40:00.394862          44850
15:40:03 2019-04-26 15:40:04.179730          44850
15:40:05 2019-04-26 15:40:05.183926          44850
15:40:08 2019-04-26 15:40:08.460073          44850
15:40:33 2019-04-26 15:40:33.447601          44850
         2019-04-26 15:40:33.946604          44850
15:41:23 2019-04-26 15:41:23.909181          44850
15:41:24 2019-04-26 15:41:25.172824          44850
15:41:29 2019-04-26 15:41:29.462690          44850
15:41:38 2019-04-26 15:41:38.797371          44850
15:41:40 2019-04-26 15:41:40.561732          44850
15:42:11 2019-04-26 15:42:11.847501          44850
15:42:23 2019-04-26 15:42:23.451729          44850
15:43:02 2019-04-26 15:43:02.556096          44850
15:43:25 2019-04-26 15:43:25.559441          44850
15:43:30 2019-04-26 15:43:30.857148          44850
15:43:58 2019-04-26 15:43:58.610704          44850
15:44:18 2019-04-26 15:44:18.792572          44850
15:45:00 2019-04-26 15:45:02.439976          44850
15:45:01 2019-04-26 15:45:02.440602          44850
15:45:27 2019-04-26 15:45:27.413961          44850

[54255 rows x 8 columns]